<package format="2">
  <name>ugv_description</name>
  <version>1.0.0</version>
  <description>
	  <p>xacro->URDF Description package for UGV</p>
  </description>
  <author>Stuart Johnson</author>
  <maintainer email="stuart.g.johnson@gmail.com" />
  <license>Apache-2.0</license>
  <depend>robot_state_publisher</depend>
  <depend>rviz2</depend>
  <depend>joint_state_publisher_gui</depend>
  <export>
    <architecture_independent />
    <build_type>ament_cmake</build_type>
  </export>
</package>
